language: python
python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6
    - pypy
    - pypy3
install:
    - pip install -U -r requirements.txt
    - buildout -v
script:
    - bin/test-grok
notifications:
    email: false
